# Generated by Django 5.1 on 2024-08-22 17:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.household')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('shopping_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shoppingitem')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shoppinglist')),
            ],
        ),
        migrations.CreateModel(
            name='WeekList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('starting_date', models.DateField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.household')),
            ],
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='week_list',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.weeklist'),
        ),
        migrations.CreateModel(
            name='MealsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_list', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.weeklist')),
            ],
        ),
    ]
