# Generated by Django 5.1 on 2024-08-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_household_shoppinglist_shoppingitem_shoppinglistitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='name',
            field=models.CharField(default='brood', max_length=256),
            preserve_default=False,
        ),
    ]
