# Generated by Django 5.1 on 2024-08-22 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shoppingitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
