version: '3'
name: ${basename}
services:
  frontend:
    build:
      context: ./frontend
      args:
        - backend_url=${backend_url}
        - version=${version}
    ports:
      - ${frontend_port}:80

  backend:
    build: ./backend
    environment:
      - APP_VERSION=${version}
      - BASENAME=${basename}
    ports:
      - ${backend_port}:5000
    volumes:
      - data:/code/data

volumes:
  data: